name: deepsort
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pip=21.1.2
  - pytorch=1.4.0
  - torchvision=0.5.0
  - pip:
      - atomicwrites==1.3.0
      - attrs==19.3.0
      - colorama==0.4.3
      - easydict==1.9
      - entrypoints==0.3
      - et-xmlfile==1.0.1
      - flake8==3.7.9
      - flake8-import-order==0.18.1
      - mportlib-metadata==1.6.0
      - jdcal==1.4.1
      - joblib==0.14.1
      - numpy==1.18.2
      - lap==0.4.0
      - ccabe==0.6.1
      - ore-itertools==8.2.0
      - motmetrics==1.2.0
      - opencv-python==4.2.0.34
      - openpyxl==3.0.3
      - packaging==20.3
      - andas==1.0.3
      - illow==8.3.2
      - pluggy==0.13.1
      - py==1.10.0
      - py-cpuinfo==5.0.0
      - pycodestyle==2.5.0
      - pyflakes==2.1.1
      - pyparsing==2.4.7
      - pytest==5.4.1
      - ytest-benchmark==3.2.3
      - python-dateutil==2.8.1
      - ytz==2019.3
      - yYAML==5.4
      - cikit-learn==0.22.2.post1
      - scipy==1.4.1
      - six==1.14.0
      - sklearn==0.0
      - Vizer==0.1.5
      - wcwidth==0.1.9
      - xmltodict==0.12.0
      - zipp==3.1.0
